#!/bin/bash

set -e

case "$1" in
    remove|pruge)
        echo "* Restoring google-chrome's APT repository, regardless of chronic HTTP failures"
        dpkg-divert --rename --remove /etc/apt/sources.list.d/google-chrome.list
        echo "* Restoring Chritopher Korn VLC PPA, in case it gets back to life"
        dpkg-divert --rename --remove /etc/apt/sources.list.d/vlc.list
    ;;
esac

exit 0
